name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run eslint
      - run: npm run build
      - run: npm run test

      - name: Get commit author name
        id: author
        run: |
          echo "name=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT

      - name: Notify failure
        uses: rjstone/discord-webhook-notify@v2
        if: failure()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: error
          details: Build failed ðŸ¤¦â€â™‚ï¸
          title: ${{ github.repository }}
          description: ${{ steps.author.outputs.name }} - https://github.com/${{ github.repository }}/commit/${{ github.sha }}

  cypress_tests:
    runs-on: ubuntu-latest
    needs: build_and_unit_tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - uses: cypress-io/github-action@v5
        with:
          command: npm run cypress:test
          start: npm run start-prod
          wait-on: http://localhost:5000

  playwright_tests:
    runs-on: ubuntu-latest
    needs: build_and_unit_tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npx playwright install
      - run: npm run test:e2e

  deploy:
    runs-on: ubuntu-latest
    needs: [cypress_tests, playwright_tests]
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')
    steps:
      - uses: actions/checkout@v4
      - uses: sws2apps/render-deployment@v1.8.0
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false

  tag_release:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get commit author name
        id: author
        run: |
          echo "name=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT

      - name: Notify success
        uses: rjstone/discord-webhook-notify@v2
        if: success()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          details: A new version has been released ðŸ˜ƒ
          title: ${{ github.repository }}
          description: ${{ steps.author.outputs.name }} - https://github.com/${{ github.repository }}/commit/${{ github.sha }}
